blog/urls.py
from django.urls import path
from .views import ArticleListView, ArticleDetailsView, CategoryListView, ArticleCreateView, ArticleUpdateView

app_name = "blog"
urlpatterns = [
    path('', ArticleListView.as_view(), name="index"),
    path('article/add/', ArticleCreateView.as_view(), name='article-add'),
    path('<slug:category>/<slug:slug>/edit/',
         ArticleUpdateView.as_view(), name="article-edit"),
    path('<slug:category>/<slug:slug>', ArticleDetailsView.as_view(), name="article"),
    path('<slug:slug>', CategoryListView.as_view(), name="category")
]

blog/models.py
# coding=utf-8
"""Blog models for Django

Models needed to setup a general blog."""

import shortuuid
from django import urls
from django.conf import settings
from django.db import models
from django.utils import timezone, text


# Create your models here.


class Profile(models.Model):
    """The `Profile` model is an extension to the base Django User model."""

    class Meta:
        verbose_name = "profil"

    CAMPUSES = (
        ('blois', 'Blois'),
        ('bourges', 'Bourges')
    )

    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name="utilisateur")
    headshot = models.ImageField(
        blank=True, null=True, verbose_name="photo de profil")
    campus = models.CharField(max_length=24, choices=CAMPUSES)

    def has_perm(self, perm, obj=None):
        return self.user.has_perm(perm, obj)

    @property
    def full_name(self):
        """Gets the full name of a user.

        For example: `<User: John Doe>.full_name` will give `John Doe`."""
        return "{} {}".format(self.user.first_name, self.user.last_name)

    @property
    def full_name_short(self):
        """Gets the short 'full name' of a user.

        For example: `<User: John Doe>.full_name_short` will give `J. Doe`."""
        return "{}. {}".format(str(self.user.first_name)[:1], self.user.last_name)

    def __str__(self):
        return self.full_name_short


class Category(models.Model):
    """Model that regroups several articles under one category."""

    class Meta:
        verbose_name = "catégorie"

    name = models.CharField(max_length=140, verbose_name="nom", unique=True)
    description = models.TextField(max_length=350)
    slug = models.SlugField(unique=True, max_length=50)

    def save(self, *args, **kwargs):
        # self.slug = text.slugify(self.name[:50])
        slug = text.slugify(self.name)
        if len(slug) > 50:
            self.slug = "{}-{}".format(
                slug[:41],
                shortuuid.ShortUUID().random(length=8)
            )
        else:
            self.slug = slug

        super(Category, self).save(*args, **kwargs)

    def __str__(self):
        return self.name


class Article(models.Model):
    """Piece of a blog, owned by a category."""
    title = models.CharField(max_length=140, verbose_name="titre")
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, verbose_name="catégorie")
    author = models.ForeignKey(
        Profile, on_delete=models.CASCADE, verbose_name="auteur")
    intro = models.TextField(max_length=350)
    image = models.ImageField(blank=True, null=True, upload_to="blog/articles")
    contents = models.TextField(verbose_name="contenu")
    created = models.DateTimeField(verbose_name="créé", auto_now_add=True)
    modified = models.DateTimeField(verbose_name="modifié", auto_now=True)
    views = models.IntegerField(default=0, verbose_name="vue")
    slug = models.SlugField(unique=True, max_length=50)

    @property
    def trending_weight(self):
        """Gets a popularity metric through a simple calculation: number of views over time."""
        lifetime = timezone.now() - self.created
        return self.views / lifetime.total_seconds()

    def get_absolute_url(self):
        """Returns a reversed string that points to the public resource."""
        return urls.reverse('blog:article', args=[self.category.slug, self.slug])

    def save(self, *args, **kwargs):
        if not self.id:

            slug = text.slugify(self.title)
            if len(slug) > 50:
                self.slug = "{}-{}".format(
                    slug[:41],  # slug.max_length - 9
                    shortuuid.ShortUUID().random(length=8)
                )
            else:
                self.slug = slug

        super(Article, self).save(*args, **kwargs)

    def __str__(self):
        return "#{}. {}".format(self.id, self.title)

blog/views.py
"""Blog views."""
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.views.generic import DetailView, UpdateView, CreateView
from django.views.generic.list import ListView

from .models import Article, Category, Profile


class ArticleListView(ListView):
    model = Article
    template_name = "blog/blog.html"
    paginate_by = 10

    def get_queryset(self, **kwargs):
        # delta = timezone.now() - timedelta(days=30)
        # return Article.articles.filter(created__gte=delta).order_by('-created')
        return Article.objects.order_by('-created')

    def get_context_data(self, queryset=None, **kwargs):
        perms = {
            'articles': {
                'create': self.request.user.has_perm('blog.create_article'),
                'remove': self.request.user.has_perm('blog.remove_article')
            }
        }

        context = super().get_context_data(queryset=queryset, **kwargs)
        context['article_title'] = "Article récents"
        context['perms'] = perms

        return context


class CategoryListView(ArticleListView):
    slug_field = 'slug'

    def get_queryset(self, **kwargs):
        qs = Article.objects.all()
        if self.kwargs.get('slug'):
            qs = qs.filter(category__slug=self.kwargs['slug'])
        return qs.order_by('-created')

    def get_context_data(self, queryset=None, **kwargs):
        context = super().get_context_data(queryset, **kwargs)
        context['article_title'] = "Articles"

        if self.kwargs.get('slug'):
            category = Category.objects.get(slug=self.kwargs['slug'])
            context['article_title'] = category.name
            context['category'] = category

            perms = context['perms']
            perms['category'] = {
                'edit': self.request.user.has_perm('blog.change_category'),
                'remove': self.request.user.has_perm('blog.remove_category')
            }
            context['perms'] = perms

        return context


class ArticleDetailsView(DetailView):
    model = Article
    template_name = 'blog/article.html'
    slug_field = 'slug'

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        obj.views += 1
        obj.save()

        return obj

    def get_context_data(self, **kwargs):
        perms = {
            'edit': self.request.user.has_perm('blog.change_article', self.object),
            'remove': self.request.user.has_perm('blog.delete_article', self.object)
        }

        context = super().get_context_data(**kwargs)
        context['perms'] = perms

        return context


class ArticleCreateView(CreateView, PermissionRequiredMixin):
    model = Article
    fields = ['title', 'image', 'category', 'intro', 'contents']
    template_name = "blog/article_edit.html"

    def form_valid(self, form):
        form.instance.author = Profile.objects.get(user=self.request.user)

        return super().form_valid(form)

    def has_permission(self):
        return self.request.user.has_perm('blog.create_article')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['mode'] = 'create'
        context['categories'] = Category.objects.all()

        return context

    def get_success_url(self):
        return self.object.get_absolute_url()


class ArticleUpdateView(UpdateView, PermissionRequiredMixin):
    model = Article
    fields = ['title', 'image', 'category', 'intro', 'contents']
    template_name = "blog/article_edit.html"

    def has_permission(self):
        return self.request.user.has_perm('blog.change_article', self.object)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['mode'] = 'edit'
        context['categories'] = Category.objects.all()

        return context

    def get_success_url(self):
        return self.object.get_absolute_url()

blog/templates/blog/article.html
{% extends 'base.html' %}
{% load blog %}

{% block title %}
<title>{{object.title}} - Blog INSAction</title>
{% endblock title %} {% block css %}
<style>
    html,
    body {
        margin: 0;
        height: 100%;
    }

    p.flow-text {
        text-align: justify;
        line-break: strict;
    }
    
    blockquote {
        background: #f9f9f925;
        border-left: 10px solid #ccc;
        margin: 1.5em 10px;
        padding: 0.5em 10px;
        quotes: "\201C""\201D""\2018""\2019";
    }
    blockquote:before {
        color: #ccc;
        content: open-quote;
        font-size: 4em;
        line-height: 0.1em;
        margin-right: 0.25em;
        vertical-align: -0.4em;
    }
    blockquote p {
        display: inline;
    }

    .nowrap {
        white-space: nowrap;
        overflow-x: auto;
    }

    #top-block {
        height: 100vh;
    }

    #top-block>img {
        display: block;
        width: 100%;
        height: 100%;
        object-fit: cover;
        filter: brightness(70%) grayscale(20%);
    }

    #top-block>.container {
        position: absolute;
        bottom: 20%;
        left: 20%;
        width: 70%;
        text-shadow: 0 0 16px black;
    }

    @media (max-width: 650px) {
        #top-block>.container {
            left: 16px;
            width: 90%;
        }
    }
</style>
{% endblock css %} {% block navextend %}
  <div class="nav-wrapper transparent">
      <div class="container nowrap">
          <div class="col s12">
              <a class="breadcrumb" href="{% url 'blog:index' %}">Blogs</a>
              {% comment %} <a class="breadcrumb" href="{% url 'blog:category' object.category.slug %}">{{object.category.name}}</a> {% endcomment %}
              <a class="breadcrumb active" href="#">{{object.title}}</a>
          </div>
      </div>
  </div>
{% endblock navextend %}
{% block content %}
<header>
    <div id="top-block">
        <img src="{{object.image.url}}">
        <div class="container">
            <h1 class="white-text">{{object.title}}</h1>
            <p>
                <span class="grey-text text-lighten-3 flow-text">{{object.author.full_name}} | {{object.created | date}}</span>
            </p>
        </div>
    </div>
</header>
{% if perms.edit %}
<div class="fixed-action-btn">
    <a href="{{ object.get_absolute_url }}/edit" class="btn-floating btn-large light-green">
        <i class="large material-icons">mode_edit</i>
    </a>
</div>
{% endif %}
<main class="section container">
    <div class="container">
        <p class="flow-text">
            {{object.intro}}
        </p>
        <div class="divider"></div>
        <div id="main-article">
            {{object.contents|parse_markdown|clean}}
        </div>
    </div>
    {% if object.modified != object.created %}
    <div class="container">
        <div class="row">
            <div class="col s10 offset-s1 m6 offset-m2">
                <p class="grey-text darken-1">Modifié le {{object.modified | date}}</p>
            </div>
        </div>
    </div>
    {% endif %}
</main>
{% endblock content %}
{% block scripts %}
<script>
$(document).ready(function() {
    $('div#possibly-fixed').css('position', 'absolute').css('z-index', 997).css('width', '100%');
    $('nav.nav-extended.light-green').removeClass('light-green').addClass('transparent z-depth-0');
    $('a.brand-logo').addClass('light-green-text');
    $('nav').find('ul>li>a').removeClass('black-text').addClass('white-text');

    // Adding classes to main article
    $('#main-article>p, #main-article>blockquote>p').addClass('flow-text');
    $('#main-article').find('>p>img').addClass('right responsive-img fade-in').css('padding', '16px'); 
});
</script>
{% endblock scripts %}

blog/templates/blog/article_edit.html
{% extends 'base.html' %}
{% block title %}
    {% if mode == "create" %}
        <title>Nouvel article - Blog INSAction</title>
    {% else %}
        <title>Edition: {{object.title}} - Blog INSAction</title>
    {% endif %}
{% endblock title %}

{% block css %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
<style>
    p.flow-text {
        text-align: justify;
        line-break: loose;
    }

    .CodeMirror {
        height: 70vh;
    }
    .CodeMirror.cm-s-paper {
        cursor: text;
    }
</style>
{% endblock css %}

{% block navextend %}
<div class="nav-wrapper light-green">
    <div class="container" style="white-space: nowrap; overflow-x: auto;">
        <div class="col s12">
            {% if mode == "edit" %}
            <a href="{% url 'blog:index' %}" class="breadcrumb">Blogs</a>
            <a href="{% url 'blog:category' object.category.slug %}" class="breadcrumb">{{object.category.name}}</a>
            <a href="{{ object.get_absolute_url }}" class="breadcrumb">{{object.title|truncatewords:5}}</a>
            <a href="#" class="breadcrumb active">Edition</a>
            {% else %}
            <a href="{% url 'blog:index' %}" class="breadcrumb">Blogs</a>
            <a href="#" class="breadcrumb active">Nouvel article</a>
            {% endif %}
        </div>
    </div>
</div>
{% endblock navextend %}

{% block content %}
<main class="section">
    <div class="container">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="input-field">
                {% with widget=form.title %}
                <div class="col s12">
                    <label for="{{ widget.id_for_label }}">Titre</label>
                    <input type="text" name="{{widget.name}}" id="{{widget.id_for_label}}" class="validate" value="{% firstof widget.value '' %}" data-length="140"/>
                </div>
                {% endwith %}
            </div>
            <div class="col s12">
                <label for="{{ form.category.id_for_label }}">Catégorie</label>
                {{ form.category }}
            </div>
            <div class="input-field">
                {% with widget=form.intro %}
                <div class="col s12">
                    <label for="{{ widget.id_for_label }}">Introduction</label>
                    <textarea class="materialize-textarea"
                              name="{{ widget.name }}"
                              id="{{ widget.id_for_label }}"
                              cols="30" rows="10">{% firstof widget.value '' %}</textarea>
                </div>
                {% endwith %}
            </div>
            <div class="file-field input-field">
                {% with widget=form.image %}
                <div class="btn teal accent-4 waves-effect">
                    <span>Image</span>
                    <input type="file" name="{{widget.name}}" id="{{widget.id_for_label}}" accept="image/x-png,image/jpeg,image/gif">
                </div>
                <div class="file-path-wrapper">
                    {% if mode == "create" %}
                    <input type="text" placeholder="Ajouter une image">
                    {% else %}
                    <input type="text" placeholder="Changer l'image">
                    {% endif %}
                </div>
                {% endwith %}
            </div>
            <div class="input-field">
                {% with widget=form.contents %}
                <div class="col s12">
                    <textarea name="{{widget.name}}" id="{{widget.id_for_label}}">{% firstof widget.value '' %}</textarea>
                </div>
                {% endwith %}
            </div>
            <div class="row">
                <div class="col s6"></div>
                <div class="col s6"><a href="#" id="add-picture" class="btn teal accent-4"><i
                    class="material-icons left">add_a_photo</i>Ajouter
                    une image</a></div>
            </div>
                <button type="submit" class="btn teal accent-4"><i class="material-icons left">send</i>Envoyer</button>
            </div>
        </form>
    </div>
</main>
{% endblock content %}
{% block scripts %}
<script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>
    <script>
        var mde = new SimpleMDE({
        element: document.getElementById('{{form.contents.id_for_label|escapejs}}')
    });
        $('select').material_select();
</script>
{% endblock scripts %}

blog/templates/blog/blog.html
{% extends 'base.html' %}
{% load blog %}

{% block css %}
  <style>
      .card {
          max-height: 256px;
      }
      .card>.card-content>.card-title {
          white-space: nowrap;
          overflow-x: hidden;
      }
  </style>
{% endblock css %}

{% block navextend %}
<div class="nav-wrapper light-green darken-1">
    <div class="container">
        <div class="row">
            <div class="col s6">
                {% if category %}
                    <a class="breadcrumb" href="{% url 'blog:index' %}">Blogs</a>
                    <a class="breadcrumb active" href="#">{{category.name}}</a>
                {% else %}
                    <a class="breadcrumb active" href="{% url 'blog:index' %}">Blogs</a>
                {% endif %}
            </div>
        </div>
        {% if perms.articles.create %}
            <a href="{% url 'blog:article-add' %}" class="btn btn-floating btn-large halfway-fab waves-effect waves-light cyan accent-4"><i class="material-icons">add</i></a>
        {% endif %}
    </div>
</div>
{% endblock navextend %}

{% block content %}
{% firstof category.description description as desc %}

<main class="container">
  <h3>{{article_title}}</h3>                  
  {% if desc %}                       
    <div class="row">                         
        <div class="col s12 m8 offset-m2">    
            <p>{{desc}}</p>                   
        </div>                                
    </div>                                    
  {% endif %}
  <div class="row">
    {% if object_list %}
      {% for article in object_list %}
        {% has_perm 'blog.change_article' user article as can_edit_article %}
        <div class="col s12 l6">
          <div class="card">
            <div class="card-content">
              <span class="card-title truncate"><a class="black-text" href="{{ article.get_absolute_url }}">{{article.title}}</a></span>
              <p class="grey-text">
                  <a href="{% url 'blog:category' article.category.slug %}">{{article.category.name}}</a>
                  | {{article.author}} | {{article.created | date}}</p>
              <p>{{article.intro|truncatewords:27}}</p>
            </div>
            <div class="card-action">
                <a class="light-green-text text-darken-3" href="{{ article.get_absolute_url }}">Lire</a>
                {% if can_edit_article %}
                    <a href="{{ article.get_absolute_url }}/edit" class="cyan-text accent-4-text"><i class="tiny material-icons">mode_edit</i></a>
                {% endif %}
            </div>
          </div>
        </div>
      {% endfor %}
    {% else %}
    <p>
      Aucun article à afficher.
    </p>
    {% endif %}
  </div>
  <ul class="pagination center">
        {% if page_obj.has_previous %}
            <li class="waves-effect"><a href="{% url 'blog:index' %}?page={{page_obj.previous_page_number}}"><i class="material-icons">chevron_left</i></a></li>
        {% else %}
            <li class="disabled"><a href="#"><i class="material-icons">chevron_left</i></a></li>
        {% endif %}

        {% for index in paginator.page_range %}
          {% if index == page_obj.number %}
            <li class="active light-green"><a href="#">{{index}}</a></li>
          {% else %}
            <li class="waves-effect"><a href="{% url 'blog:index' %}?page={{index}}">{{index}}</a></li>
          {% endif %}
        {% endfor %}    

        {% if page_obj.has_next %}
            <li class="waves-effect"><a href="{% url 'blog:index' %}?page={{page_obj.next_page_number}}"><i class="material-icons">chevron_right</i></a></li>
        {% else %}
            <li class="disabled"><a href="#"><i class="material-icons">chevron_right</i></a></li>
        {% endif %}
    </ul>
</main>
{% endblock %}