blog/urls.py
from django.urls import path
from .views import ArticleListView, ArticleDetailsView, CategoryListView, ArticleCreateView, ArticleUpdateView

app_name = "blog"
urlpatterns = [
    path('', ArticleListView.as_view(), name="index"),
    path('article/add/', ArticleCreateView.as_view(), name='article-add'),
    path('<slug:category>/<slug:slug>/edit/',
         ArticleUpdateView.as_view(), name="article-edit"),
    path('<slug:category>/<slug:slug>', ArticleDetailsView.as_view(), name="article"),
    path('<slug:slug>', CategoryListView.as_view(), name="category")
]

website/urls.py
from django.urls import path
from . import views

app_name = "website"
urlpatterns = [
    path('', views.IndexList.as_view(), name="index")
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta name="theme-color" content="#7cb342"/>
    <meta http-equiv="X-UA-Compatible" content="ie=edge"> {% block title %}
    <title>INSAction - Projection de films, production de courts métrages</title>
{% endblock title %}
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
    <style>
        body {
            display: flex;
            min-height: 100vh;
            flex-direction: column;
        }

        main {
            flex: 1 0 auto;
        }

        .fade-in {
            opacity: 0;
            transition: 500ms;
            transition-property: opacity;
            transition-timing-function: ease-out;
        }

        .fade-in.visible {
            opacity: 1;
        }

        .branding {
            height: 50px;
        }

        .dropdown-content {
            min-width: 300px;
        }

        section {
            min-height: 70vh;
        }
    </style>
    {% block css %} {% endblock css %}
</head>

<body class="light-green lighten-5">
{% block navbar %}
    {% if user.is_authenticated %}
        <ul id="user-dropdown" class="dropdown-content">
            <li><a href="#"><i class="material-icons">account_box</i> Profil</a></li>
            <li class="divider"></li>
            <li><a href="{% url 'logout' %}?next={{ request.get_full_path }}"><i
                class="material-icons">person_outline</i>Déconnexion</a></li>
        </ul>
    {% else %}
        <ul id="anon-dropdown" class="dropdown-content">
            <li><a href="{% url 'login' %}?next={{ request.get_full_path }}"><i class="material-icons">person</i>
                Connexion</a></li>
            <li class="divider"></li>
            <li><a href="#"><i class="material-icons">mail_outline</i>Devenir auteur</a></li>
        </ul>
    {% endif %}
    <div id="possibly-fixed">
        <nav class="nav-extended light-green">
            <div class="nav-wrapper">
                <div class="container">
                    <a href="{% url 'website:index' %}" class="brand-logo">INSAction</a>
                    <a href="#" data-activates="mobile-nav" class="button-collapse"><i
                        class="material-icons">menu</i></a>
                    <ul class="right">
                        <li class="hide-on-med-and-down "><a href="{% url 'website:index' %}">Accueil</a></li>
                        <li class="hide-on-med-and-down">
                            <a href="#">L'association</a>
                        </li>
                        <li class="hide-on-med-and-down">
                            <a href="{% url 'blog:index' %}">Les blogs</a>
                        </li>
                        {% if user.is_authenticated %}
                            <li><a href="#" class="dropdown-button" data-activates="user-dropdown"><i
                                class="material-icons">person</i></a></li>
                        {% else %}
                            <li><a href="#" class="dropdown-button" data-activates="anon-dropdown"><i
                                class="material-icons">person_outline</i></a></li>
                        {% endif %}
                        {% if user.is_staff %}
                            <li><a href="{% url 'admin:index' %}"><i
                                class="material-icons">settings_applications</i></a></li>
                        {% endif %}
                    </ul>
                    <ul class="side-nav white black-text" id="mobile-nav">
                        <li><a href="{% url 'website:index' %}"> <i class="material-icons left">home</i>Accueil</a></li>
                        <li><a href="{% url 'blog:index' %}"><i class="material-icons left">library_books</i>Les
                            blogs</a></li>
                        <li><a href="#"><i class="material-icons left">star</i>L'association</a></li>
                    </ul>
                </div>
            </div>
            {% block navextend %} {% endblock navextend %}
        </nav>
    </div>
{% endblock navbar %} {% block content %} {% endblock content %}
<footer class="page-footer light-green darken-1">
    <div class="container">
        <div class="row">
            <div class="col s12">
                <h5>INSAction</h5>
                <div class="col s12 l8">
                    <p>L'INSAction est une organisation de l'INSA, fondée pour projeter et produire.</p>
                </div>
                <div class="col s12 l4">
                    <div class="row">
                        <div class="col s4"><a href="#"><img class="branding"
                                                             src="{% static 'insaction/img/facebook.svg' %}"
                                                             alt="Facebook"></a></div>
                        <div class="col s4"><a href="#"><img class="branding"
                                                             src="{% static 'insaction/img/instagram.svg' %}"
                                                             alt="Instagram"></a></div>
                        <div class="col s4"><a href="#"><img class="branding"
                                                             src="{% static 'insaction/img/vimeo.svg' %}"
                                                             alt="Vimeo"></a></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="footer-copyright darken-1">
        <div class="container">&copy; 2018 INSAction</div>
    </div>
</footer>

<script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.scrollfire/1.4.0/jquery.scrollfire.min.js"></script>
<script type="text/javascript"
        src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
{% block scripts %} {% endblock scripts %}
<script>
    $(document).ready(function () {
        // Activate mobile side nav
        $(".button-collapse").sideNav();

        // Fade in images
        $('.fade-in').scrollfire({
            offset: 0,
            topOffset: 150,
            bottomOffset: 150,

            onBottomIn: function (elm, distance) {
                $(elm).addClass('visible');
            }
        });
    });
</script>

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-52015533-2"></script>
<script>
    window.dataLayer = window.dataLayer || [];

    function gtag() {
        dataLayer.push(arguments);
    }

    gtag('js', new Date());

    gtag('config', 'UA-52015533-2');
    /* {% if user.is_authenticated %} */
        gtag('set', {'user-id': "{{user.username|escapejs}}"});
        /* {% endif %} */
</script>

</body>

</html>

templates/login.html
{% extends "base.html" %} {% block content %}
<main class="container">
    {% if form.non_field_errors %}
        <div class="row">
            {% for error in form.non_field_errors %}
                <div class="col s12 m6">
                    <div class="card red darken-1 white-text">
                        <div class="card-content">{{error|escape}}</div>
                    </div>
                </div>
            {% endfor %}
        </div>
    {% endif %}
    <div class="row">
        <div class="card">
            <form method="POST">
                {% csrf_token %}
                <div class="card-content">
                    <span class="card-title">Connexion</span>
                    {% for field in form %}
                        <div class="input-field">
                            {{ field.label_tag }} {{ field }}
                        </div>
                        {% for err in field.errors %}
                            <p class="red lighten-1">{{err | escape}}</p>
                        {% endfor %}
                    {% endfor %}
                </div>
                <div class="card-action">
                    <button type="submit" class="btn teal accent-4 waves-effect waves-light">
                        Connexion <i class="material-icons right">send</i>
                </div>
            </form>
        </div>
    </div>
</main>
{% endblock content %} {% block scripts %}
<script>
    $(document).ready(function () {
        Materialize.updateTextFields();
    })
</script>
{% endblock scripts %}

templates/maintenance.html
{% extends "base.html" %}

{% block css %}
  <style>
      body {
          background-color: black;
          overflow-y: hidden;
      }
      .animate {
          opacity: 0;
          transition: opacity 1.5s ease-out;
      }
      .animate.ready {
          opacity: 1;
      }
  </style>
{% endblock css %}

{% block scripts %}
  <script>
    
    $(document).ready(function() {
        setTimeout(function() {
            $('#title').addClass('ready');
            setTimeout(function() {
                $('#video').addClass('ready');
            }, 5e3);
        }, 1000);
    });

  </script>
{% endblock scripts %}

{% block navbar %}
  
{% endblock navbar %}

{% block content %}
  <header class="black white-text valign-wrapper" style="height: 100vh;">
      <div id="title" class="container animate">
          <div class="row right">
              <h1 class="light-green-text">INSAction</h1>
              <h4>Une association <span class="red-text accent-3">INSA</span>, pour projeter et produire le septième art.</h4>
              <p class="grey-text center">Coming soon...</p>
          </div>
      </div>
      
  </header>
{% endblock content %}